### ISSUE TITLE
运行官网的例子 报错。

### ISSUE THREAD

**Issue by qiushangzhe** [thinkkoa/thinkorm#1]
let user = thinkorm.require(path.reslove('./user.js'));
                                 ^

TypeError: path.reslove is not a function
    at Object.<anonymous> (/Users/qiusz/qiushangzhe/myCode/mysqlTest/app.js:26:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by richenlin** [comment]
thinkorm.require入参为模型类文件绝对路径

path.resolve，文档拼写错误  -_-|||
