### ISSUE TITLE
migrate迁移忽略特殊字段的索引

### ISSUE THREAD

**Issue by elegance1412** [thinkkoa/thinkorm#2]
字段类型为array、json时，加索引时：
```
this.fields = {
    province_list: {
         type: 'array',
         defaultsTo: [],
         index: true
    },
}
```
报如下错误：

Unhandled rejection Error: ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT column 'province_list' used in key specification without a key length
    at Query.Sequence._packetToError (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Protocol._enqueue (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/mysql/lib/Connection.js:208:25)
    at /Users/chenjp/workspace/projects_react/DataCenter/node_modules/thinkorm_adapter_mysql/node_modules/think_lib/index.js:610:16
    at Promise._execute (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/bluebird/js/release/promise.js:79:10)
    at /Users/chenjp/workspace/projects_react/DataCenter/node_modules/thinkorm_adapter_mysql/node_modules/think_lib/index.js:609:16
    at connect.then.conn (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/thinkorm_adapter_mysql/lib/index.js:185:20)
    at run (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/core-js/library/modules/es6.promise.js:66:22)
    at /Users/chenjp/workspace/projects_react/DataCenter/node_modules/core-js/library/modules/es6.promise.js:79:30
    at flush (/Users/chenjp/workspace/projects_react/DataCenter/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by richenlin** [comment]
fix by version  thinkorm@2.1.1
